apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "replicationcontrollers", "services", "events"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-binding
subjects:
- kind: ServiceAccount
  name: falco-sa
  namespace: security
roleRef:
  kind: ClusterRole
  name: falco-clusterrole
  apiGroup: rbac.authorization.k8s.io