apiVersion : v1
kind : ServiceAccount
metadata :
  name : frontend-sa
  namespace : apps
  annotations :
    eks.amazonaws.com/role-arn : arn:aws:iam::ACCOUNT_ID:role/frontend-pod-role #replace ACCOUNT_ID with your AWS account ID
automountServiceAccountToken : false